cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('search/', views.search, name="search")
]

kedaiKopi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', include('admin_honeypot.urls')),
    path('admin12/', admin.site.urls),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('payment/', include('payment.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))

class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'block w-full py-3 text-gray-700 bg-white border border-gray-300 rounded-lg focus:border-blue-400 focus:ring focus:ring-blue-300 focus:outline-none'
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from product.models import Product
from product.models import Category
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView as AuthLoginView
from .forms import SignupForm, LoginForm
from django.contrib import messages

def search(request):
    q = request.GET.get('q', '')  # Default ke string kosong jika 'q' tidak ada
    results = []

    if q:  # Jika parameter 'q' memiliki nilai
        results = Product.objects.filter(name__icontains=q)  # Cari produk berdasarkan nama
    return render(request, 'core/search_results.html', {
        'query': q,
        'results': results,
    })

def home(request):
    products = Product.objects.filter(is_sold=False)
    latest_products = Product.objects.order_by('-date_added')[:3]
    categories = Category.objects.all()
    return render(request, 'core/home.html', {
        'categories': categories,
        'products': products,
        'latest_products': latest_products,
    })

class LoginView(AuthLoginView):
    template_name = 'core/login.html'
    authentication_form = LoginForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return redirect('core:home')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:login')  # Redirect to login page after successful signup
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {'form': form})

def logout_user(request):
    logout(request)
    messages.success(request, "You Were Logged Out")
    return redirect('core:home')

core/templates/core/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block tittle %}{% endblock %}</title>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'Logo.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
    {% tailwind_css %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</head>
<body>
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
    <div class="max-w-screen-2xl flex flex-wrap items-center justify-between p-4">
    <a href="{% url 'core:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img src="{% static 'Logo.png' %}" class="h-10" alt="">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Kedai 4</span>
    </a>

    <!--Navbar desktop screen-->
    <form action="{% url 'core:search' %}" method="get" class="flex md:order-2 space-x-3 md:space-x-4 rtl:space-x-reverse">
        <div class="relative hidden md:w-56 md:flex">
            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
              <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
              </svg>
              <span class="sr-only">Search icon</span>
            </div>
            <input type="text" name="q" id="search-navbar" class="w-full md:max-w-2xl p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
        </div>
        <button id="searchButton" type="submit" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 border border-gray-300" aria-controls="navbar-sticky" aria-expanded="false">
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
            <span class="sr-only">Search</span>
        </button>
        {% if request.user.is_authenticated %}
          <a href="{% url 'cart:cart_summary' %}" class="flex items-center justify-center bg-white">
            <div class="relative scale-75">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-8 w-8 text-gray-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
              </svg>
              <span id="cart_quantity" class="absolute -top-2 left-4 rounded-full bg-red-500 text-center w-5 h-5 text-sm text-white">{{ cart|length }}</span>
            </div>
          </a>
          <!-- Tombol logout jika pengguna sudah login -->
          <a href="{% url 'core:logout' %}" type="button" class="text-white bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center">Logout</a>      
        {% else %}
        <!-- Tombol Login dan Register jika pengguna belum login -->
          <a href="{% url 'core:login' %}" type="button" class="bg-transparent border border-blue-700 text-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center">Login</a>      
          <a href="{% url 'core:signup' %}" type="button" class="text-white bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center">Register</a>      
        {% endif %}
      </form>

    <!--Navbar mobile screen-->
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
        <div class="relative mt-3 md:hidden">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
          </div>
          <input type="text" id="search-navbar" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500" placeholder="Search...">
        </div>
    </div>
    </div>

    <script>
        document.getElementById("searchButton").addEventListener("click", function() {
            var menu = document.getElementById("navbar-search");
            menu.classList.toggle("hidden"); 
        });
    </script>
</nav>

    {% block content %}
    {% endblock %}
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}


{% block tittle %}Kopi4{% endblock %}

{% block content %}
<div class="bg-white">
    <!-- Content -->
    <main class="my-28">
        <div class="container mx-auto px-6">
            <h2 class="text-2xl font-bold tracking-tight text-gray-900">Produk Terkini..</h2>
            <div class="swiper-container mt-6 h-64 w-full rounded-md overflow-hidden bg-cover bg-center">
                <div class="swiper-wrapper">
                    {% for product in latest_products %}
                    <div class="swiper-slide h-64 bg-cover bg-center" style="background-image: url('{{ product.image.url }}')">
                        <div class="bg-gray-900 bg-opacity-30 flex items-center h-full">
                            <div class="px-10 max-w-xl">
                                <h2 class="text-3xl text-white font-semibold">{{ product.name }}</h2>
                                <p class="my-6 text-white">{{ product.description|truncatewords:20 }}</p>
                                <a href="{% url 'product:detail' product.id %}" class="flex items-center mt-4 px-3 py-2 bg-blue-700 text-white w-40 text-sm uppercase font-medium rounded-lg hover:bg-blue-800 focus:outline-none focus:bg-blue-500">
                                    <span>Shop Now</span>
                                    <svg class="h-5 w-5 mx-2" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                                        <path d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="bg-white z-0">
                <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-7xl">
                    <h2 class="text-2xl font-bold tracking-tight text-gray-900">Produk</h2>
                    <div class="mt-6 grid grid-cols-2 gap-x-6 gap-y-10 lg:grid-cols-4 xl:gap-x-8">
                        {% for product in products %}
                        <div class="group relative">
                        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                            <img src="{{ product.image.url }}" alt="Coffee" class="h-full w-full object-cover object-center lg:h-full lg:w-full">
                        </div>
                        <div class="mt-4 flex justify-between">
                            <div>
                            <h3 class="text-sm text-gray-700">
                                <a href="{% url 'product:detail' product.id %}">
                                <span aria-hidden="true" class="absolute inset-0"></span>
                                {{ product.name }}
                                </a>
                            </h3>
                            <p class="mt-1 text-sm text-gray-500">{{ product.category }}</p>
                            </div>
                            {% load l10n %}
                            <p class="text-sm font-medium text-gray-900">Rp. {{ product.price|localize }}</p>
                        </div>
                        </div>
                        {% endfor %}
                
                        <!-- More products... -->
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    <footer class="bg-gray-200">
        <div class="container mx-auto px-6 py-3 flex justify-between items-center">
            <a href="#" class="text-xl font-bold text-gray-500 hover:text-gray-400">Brand</a>
            <p class="py-2 text-gray-500 sm:py-0">All rights reserved</p>
        </div>
    </footer>
</div>

<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<script>
    // Initialize Swiper
    const swiper = new Swiper('.swiper-container', {
        loop: true,
        autoplay: {
            delay: 5000, // Slide every 10 seconds
            disableOnInteraction: false, // Allow interaction to keep autoplay running
        },
    });
</script>
{% endblock %}

core/templates/core/login.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% tailwind_css %}
</head>
<body>
    <div class="flex w-full flex-wrap">
        <div class="flex w-full flex-col md:w-1/2 lg:w-1/3">
          <div class="flex justify-center pt-12 md:-mb-24 md:justify-start md:pl-12">
            <a href="{% url 'core:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
                <img src="{% static 'Logo.png' %}" class="h-10" alt="Kopi4 Logo">
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Kopi4</span>
            </a>
          </div>
          <div class="my-auto flex flex-col justify-center px-6 pt-8 sm:px-24 md:justify-start md:px-8 md:pt-0 lg:px-12">
            <p class="text-center text-3xl font-bold">Login</p>
            <p class="mt-2 text-center">Login to your account to access full features</p>
            <form class="flex flex-col pt-3 md:pt-8" method="post" action="{% url 'core:login' %}">
                {% csrf_token %}
                <div class="relative flex items-center gap-8">
                    {{ form.username }}
                </div>
                <div class="relative flex items-center mt-4">
                    {{ form.password }}
                </div>
                <button class="mt-6 w-full px-6 py-3 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-700 rounded-lg hover:bg-blue-800 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                    Login
                </button>
            </form>
            <div class="mt-6 text-center ">
                <a href="{% url 'core:signup' %}" class="text-sm text-blue-500 hover:underline dark:text-blue-400">
                    Don't have an account?
                </a>
            </div>
          </div>
        </div>
        <div class="pointer-events-none hidden select-none bg-black shadow-2xl md:block md:w-1/2 lg:w-2/3">
            <img class="h-screen w-full object-cover opacity-90" src="{% static 'photo2.jpg' %}" />
          </div>
    </div>
</body>
</html>

core/templates/core/search_results.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="text-2xl font-bold">Hasil pencarian</h1>

<!-- Menampilkan Query -->
{% if query %}
    <p class="text-gray-600">Results for: <strong>{{ query }}</strong></p>
{% endif %}

<!-- Menampilkan Hasil Pencarian -->
{% if results %}
<div class="bg-white z-0">
    <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-7xl">
        <h2 class="text-2xl font-bold tracking-tight text-gray-900">Produk</h2>
        <div class="mt-6 grid grid-cols-2 gap-x-6 gap-y-10 lg:grid-cols-4 xl:gap-x-8">
            {% for product in results %}
            <div class="group relative">
            <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                <img src="{{ product.image.url }}" alt="Coffee" class="h-full w-full object-cover object-center lg:h-full lg:w-full">
            </div>
            <div class="mt-4 flex justify-between">
                <div>
                <h3 class="text-sm text-gray-700">
                    <a href="{% url 'product:detail' product.id %}">
                    <span aria-hidden="true" class="absolute inset-0"></span>
                    {{ product.name }}
                    </a>
                </h3>
                <p class="mt-1 text-sm text-gray-500">{{ product.category }}</p>
                </div>
                {% load l10n %}
                <p class="text-sm font-medium text-gray-900">Rp. {{ product.price|localize }}</p>
            </div>
            </div>
            {% endfor %}
    
            <!-- More products... -->
        </div>
    </div>
</div>
{% else %}
<p class="text-gray-500 mt-4">No results found.</p>
{% endif %}
{% endblock %}

core/templates/core/signup.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    {% tailwind_css %}
</head>
<body>
    <div class="flex w-full flex-wrap">
        <div class="flex w-full flex-col md:w-1/2 lg:w-1/3">
          <div class="flex justify-center pt-12 md:-mb-24 md:justify-start md:pl-12">
            <a href="{% url 'core:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
                <img src="{% static 'Logo.png' %}" class="h-10" alt="">
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Kopi4</span>
            </a>
          </div>
          <div class="my-auto flex flex-col justify-center px-6 pt-8 sm:px-24 md:justify-start md:px-8 md:pt-0 lg:px-12">
            <p class="text-center text-3xl font-bold">Register</p>
            <p class="mt-2 text-center">Create account to access full features</p>
            <form class="flex flex-col pt-3 md:pt-8" method="post" action=".">
                {% csrf_token %}

                <div class="relative flex items-center gap-8">
                    {{ form.username }}
                </div>
    
                <div class="relative flex items-center mt-6">
                    {{ form.email }}
                </div>
    
                <div class="relative flex items-center mt-4">
                    {{ form.password1 }}
                </div>
    
                <div class="relative flex items-center mt-4">
                    {{ form.password2 }}
                </div>
                
                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-6 bg-red-100 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <div class="mt-6">
                    <button class="w-full px-6 py-3 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-700 rounded-lg hover:bg-blue-800 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                        Submit
                    </button>
    
                    <div class="mt-6 text-center ">
                        <a href="{% url 'core:login' %}" class="text-sm text-blue-500 hover:underline dark:text-blue-400">
                            Already have an account?
                        </a>
                    </div>
                </div>
            </form>
          </div>
        </div>
        <div class="pointer-events-none hidden select-none bg-black shadow-2xl md:block md:w-1/2 lg:w-2/3">
          <img class="h-screen w-full object-cover opacity-90" src="{% static 'photo2.jpg' %}" />
        </div>
    </div>
    
</body>
</html>