cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('search/', views.search, name="search")
]

kedaiKopi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', include('admin_honeypot.urls')),
    path('admin12/', admin.site.urls),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('payment/', include('payment.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from product.models import Product
from django.http import JsonResponse, HttpResponseBadRequest
import stripe
from django.conf import settings


def cart_summary(request):
    cart = Cart(request)
    cart_products = cart.get_prods
    quantities = cart.get_quants
    totals = cart.cart_total()
    tax = cart.tax_total()
    grand_total = cart.grand_total()
    return render(request, "cart_summary.html", {"cart_products": cart_products, "quantities": quantities, "totals": totals, "tax": tax, "grand_total": grand_total,})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, quantity=product_qty)

        cart_quantity = cart.__len__()

        #response = JsonResponse({'Product Name: ': product.name})
        response = JsonResponse({'qty: ': cart_quantity})
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        
        cart.delete(product=product_id)

        response = JsonResponse({'product': product_id})
        return response


def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        cart.update(product=product_id, quantity=product_qty)

        response = JsonResponse({'qty': product_qty})
        return response
        #return redirect('cart_summary')

cart/templates/cart_summary.html
{% extends 'core/base.html' %}

{% block tittle %}Cart{% endblock %}

{% block content %}
<section class="bg-white py-16 antialiased md:py-20">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="mt-6 sm:mt-8 md:gap-6 lg:flex lg:items-start xl:gap-8">
      <div class="mx-auto w-full flex-none lg:max-w-2xl xl:max-w-4xl">
        <div class="space-y-6">
          {% for product in cart_products %}
          <div class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm md:p-2">
            <div class="space-y-4 md:flex md:items-center md:justify-between md:gap-6 md:space-y-0">
              <a href="#" class="shrink-0 md:order-1">
                <img class="h-32 w-32 rounded-lg" src="{{ product.image.url }}" alt="imac image" />
              </a>
              <div class="flex items-center justify-between md:order-3 md:justify-end">
                <div class="py-2 px-3 rounded-2xl" data-hs-input-number="">
                  <div class="w-full flex justify-between items-center gap-x-5">
                      <div class="gap-y-2">
                          <span class="block text-xs text-gray-500 dark:text-neutral-400">
                          Select quantity
                          </span>
                          <select class="form-select form-select-sm w-full border-0 rounded-lg border-transparent focus:border-transparent focus:ring-0" id="select{{ product.id }}" >
                              {% for key, value in quantities.items %}
                                {% if key == product.id|slugify %}
                                  <option selected>{{ value }}</option>
                                {% endif %}
                              {% endfor %}
                              <option value="1">1</option>
                              <option value="2">2</option>
                              <option value="3">3</option>
                              <option value="4">4</option>
                          </select>
                      </div>
                  </div>
              </div>
                <div class="text-end md:order-4 md:w-32">
                  <p class="text-base font-bold text-gray-900">Rp. {{ product.price }}</p>
                </div>
              </div>

              <div class="w-full min-w-0 flex-1 space-y-4 md:order-2 md:max-w-md">
                <a href="#" class="text-base font-medium text-gray-900 hover:underline">{{ product.name }}</a>

                <div class="flex items-center gap-4">
                  <button type="button" data-index="{{ product.id }}" class="btn btn-secondary update-cart inline-flex items-center text-sm font-medium text-gray-500 hover:text-gray-900 hover:underline">
                    Update
                  </button>

                  <button type="button" data-index="{{ product.id }}" class="btn btn-danger delete-product inline-flex items-center text-sm font-medium border p-2 border-red-600 rounded-2xl text-red-600 hover:underline">
                    <svg class="me-1.5 h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18 17.94 6M18 18 6.06 6" />
                    </svg>
                    Remove
                  </button>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      <div class="mx-auto mt-6 max-w-4xl flex-1 space-y-6 lg:mt-0 lg:w-full">
        <div class="space-y-4 rounded-lg border border-gray-200 bg-white p-4 shadow-sm sm:p-6">
          <p class="text-xl font-semibold text-gray-900">Order summary</p>

          <div class="space-y-4">
            <div class="space-y-2">
              <dl class="flex items-center justify-between gap-4">
                <dt class="text-base font-normal text-gray-500">Original price</dt>
                <dd class="text-base font-medium text-gray-900">Rp. {{ totals }}</dd>
              </dl>

              <dl class="flex items-center justify-between gap-4">
                <dt class="text-base font-normal text-gray-500">Tax (10%)</dt>
                <dd class="text-base font-medium text-gray-900">Rp. {{ tax }}</dd>
              </dl>
            </div>

            <dl class="flex items-center justify-between gap-4 border-t border-gray-200 pt-2">
              <dt class="text-base font-bold text-gray-900">Total</dt>
              <dd class="text-base font-bold text-gray-900">Rp. {{ grand_total }}</dd>
            </dl>
          </div>

          <a href="#" class="flex bg-blue-700 w-full items-center justify-center rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300">Checkout</a>

          <div class="flex items-center justify-center gap-2">
            <span class="text-sm font-normal text-gray-500"> atau </span>
            <a href="{% url 'core:home' %}" title="" class="inline-flex items-center gap-2 text-sm font-medium text-primary-700 underline hover:no-underline">
              Lanjut belanja
              <svg class="h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5m14 0-4 4m4-4-4-4" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  //update cart
 $(document).on('click', '.delete-product', function(e){
    e.preventDefault();
    //var productid = $(this).data('index'); 
    $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_delete" %}',
        data: {
            product_id: $(this).data('index'),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },

        success: function(json){
            //document.getElementById("cart_quantity").textContent = json.qty
            location.reload();
        },

        error: function(xhr, errmsg, err){

        }
    })
})

//delete cart
$(document).on('click', '.update-cart', function(e){
    e.preventDefault();
    var productid = $(this).data('index'); 
    $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_update" %}',
        data: {
            product_id: $(this).data('index'),
            product_qty: $('#select' + productid + ' option:selected').val(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },

        success: function(json){
            //document.getElementById("cart_quantity").textContent = json.qty
            location.reload();
        },

        error: function(xhr, errmsg, err){

        }
    })
})
</script>
{% endblock %}